📝 Document all the features
CodingZeal/redwood-template-app pull request #111
Opened 2022-10-28 20:02 UTC by craineum

# Pull Request

## Story

Fix #83 #60 #82 #81 #69 

## Description

Document features

## Affected Areas

Readme documentation

## Definition of Done

- [x] README updated
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/3orifaQEOagjYJ1EXe/giphy.gif)

2022-10-28 20:49 UTC, house9 approved these changes
LGTM

came across one possible typo

2022-10-28 20:49 UTC, house9 commented on README.md
> +
`The data is structure` -> The data is structured

2022-10-28 21:10 UTC, zan-rosenthal requested changes

2022-10-28 21:10 UTC, zan-rosenthal commented on README.md
> +Tests are located next to the files they are testing. Making it easy to find associated tests. We nest `describe` blocks for context when certain setup or data is required. Some tests are placeholder
Maybe add an example of the naming pattern for a file and for a test here.

2022-10-28 21:10 UTC, zan-rosenthal commented on README.md
> +Feature testing is brittle and a pain to maintain. In order to make this easier we only keep happy path tests around. We also write tests for development that may not be happy path, that we then dele
Do the development tests get committed? If users of the template don't see them, do we need this sentence?

2022-10-31 19:03 UTC, zan-rosenthal approved these changes

2022-10-31 19:04 UTC, merged