🧹 Chore/68 admin user
CodingZeal/redwood-template-app pull request #131
Opened 2022-11-15 23:48 UTC by nataliadiaz2

## Story

Fix #68 Admin- User Testing

## Description

Admin-User test going through CRUD

## Solution

Admin going through CRUD regarding users

## Affected Areas

E2E Testing

## Tests

CRUD Admin-User test

## Was this feature tested on all browsers?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif)

2022-11-16 00:08 UTC, nataliadiaz2 commented on web/tests/admin-user.spec.ts
> +  await page.goto('/login')
I tried using the global setup to login, but wasn't able to connect those.

2022-11-17 00:33 UTC, iameddieyayaya commented on web/playwright.setup.ts
> +  await adminLogin.waitForURL('http://localhost:8910')
Seems like this should be a global constant.

2022-11-17 12:54 UTC, craineum requested changes
Looking good. Some changes are needed.

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +    await page.waitForURL('/admin/users')
⚠️ There isn't any expects in here. Maybe expect a success toast message? Maybe also that the new user shows up in the list?

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +    await page.waitForURL('/admin/users')
⚠️ Should expect to see new information in the list, and shouldn't see old information in the list.

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +    await page.waitForURL('/admin/users')
⚠️ Expect the user to not be in the list.

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +    await expect(updatedMessage).toBeVisible()
➕ Maybe add one more expect that this change has taken place.

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +  await expect(admin).toBeVisible()
❓ Do we have to await everything? Including the expects?

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +  const admin = await page.locator('text=Admin').first()
❓ If we aren't using `admin` in more than one place, can we change the expect to look for this text instead of using the `page.locator` function?

2022-11-17 12:54 UTC, craineum commented on web/tests/admin-user.spec.ts
> +    await page.locator('input[name="email"]').click()
❓ Just curious, what does the `.click()` function return? Is it an instance of the input, which you could then chain the `.fill()` function onto?

2022-11-17 12:54 UTC, craineum commented on web/playwright.setup.ts
> +  await adminLogin.waitForURL('http://localhost:8910')
⚠️ Agreed, I'm sure this is available somewhere, but not sure where.

2022-11-17 12:54 UTC, craineum commented on web/playwright.setup.ts
> +  await adminLogin.waitForURL('http://localhost:8910')
❓ Also, does this run on the same port as the dev server? That seems weird to me. Like there would be a conflict.

2022-11-21 13:36 UTC, craineum approved these changes
LGTM

2022-11-21 13:37 UTC, merged