✨ Feature/120 profile email
CodingZeal/redwood-template-app pull request #140
Opened 2022-11-29 22:40 UTC by nataliadiaz2

# Pull Request

## Story

Fix #120 

## Description

Create a new page for a user to update their email.

## Solution

Create new page within Profile layout for Edit Email, Update GraphQL and services for new change, Add Edit Email component and page, Create email to be sent for new email verification, Add Email Change Verification page. 
## Screenshots

<img width="1327" alt="Screenshot 2022-11-29 at 2 34 24 PM" src="https://user-images.githubusercontent.com/101531284/204663235-da0fe669-91f8-4894-850e-6acc570de3b0.png">

## Affected Areas

Profile graphql and services, Profile Page, Edit Email page and components, Email Verification Page 

## Tests

-Tested Edit Email Page and Component rendering 
-Tested profile service to edit email 

## Was this feature tested on all browsers?

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Definition of Done

- [ ] README updated
- [X] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/9Y3KgTTTiLEHjFOXP4/giphy.gif)

2022-11-30 13:21 UTC, craineum requested changes
Looking good. The biggest thing would be to re-use the existing email verification system, so many of the "verification" files could go away.

Lastly, We would need to add a new feature/end-to-end test for the email change form. And we may need to change an existing e2e test if there was one that was verifying the existing profile change form?

2022-11-30 13:21 UTC, craineum commented on api/src/emails/email-update.ts
> +import type { User } from '@prisma/client'
♻️ This seems like some duplication. Can we re-work the sign-up email verification to be more generic to be able to use it in both places?

2022-11-30 13:21 UTC, craineum commented on api/src/graphql/profile.sdl.ts
> +    verifyEmail(token: String!): Boolean! @skipAuth
❓ Can we use the verifyEmail that is present in the `user` endpoint? I am okay if we want to move that to the `profile` endpoint/service layer if that makes more sense.

2022-11-30 13:21 UTC, craineum commented on api/src/services/profile/profile.ts
> +  validate(password, 'Existing Password', {
➕ Should have tests for these two validations.

2022-11-30 13:21 UTC, craineum commented on api/src/services/profile/profile.ts
> +  const user = await db.user.findFirstOrThrow({
♻️ If we are requiring auth, then we shouldn't need to do this lookup, the current user is already a part of the context.

2022-11-30 13:21 UTC, craineum commented on web/src/Routes.tsx
> +      <Route path="/verify-email" page={EmailChangeVerificationPage} name="emailchange" />
❓ Can we use the route from line 20 to do this verification?

2022-11-30 13:21 UTC, craineum commented on web/src/components/Profile/EditProfile/EditProfile.tsx
> +        <div className="rw-segment mt-8">
🔥 If changing the email is happening on another page, I don't think we need it in here at all.

2022-11-30 21:32 UTC, nataliadiaz2 commented on web/src/components/Profile/EditProfile/EditProfile.tsx
> +        <div className="rw-segment mt-8">
I changed the input field to a table row to display the email, should I remove the current email portion?

2022-12-01 16:22 UTC, archae0pteryx commented on api/src/services/profile/profile.scenarios.ts
> +        verifyToken: 'Tolkien',
love it.

2022-12-01 16:30 UTC, archae0pteryx commented on web/src/components/Profile/EditEmail/EditEmailForm.test.tsx
> +describe('EditPasswordForm', () => {
Most of these test assertions can really be a single one, i think. Checking that the fields exist can all be combined into a single test and if you think about it, testing that the field gets the input you type into it kinda confirms its existence... not a big deal just wanted to point that out. I think it would read less clunky all in a single, "it renders a working form" test...

2022-12-01 16:49 UTC, archae0pteryx commented on web/src/components/Profile/EditEmail/EditEmailForm.tsx
> +        <Label
The input and label fields we're using over and over with the same styling could be pulled out into a "common" components folder or even our own form package with all of the branding in one place such that we're not adding the same classes, the same kinds of handlers, the same everything over and over to each one. That makes updating something on all of them tedious. Here is an example of a component we could use over and over.

```
/* eslint-disable */
/* @ts-ignore */

import {
  FieldError,
  Label,
  PasswordField,
  TextField,
} from '@redwoodjs/forms'

interface IFormTextInputProps extends React.HTMLProps<HTMLInputElement> {
  name: string
  label: string
  placeholder?: string
  type?: string
  validationText?: string
  inputProps?: React.HTMLProps<HTMLInputElement | `...whatever the password props are`>
  labelProps?: React.HTMLProps<HTMLLabelElement>
  errorProps?: React.HTMLProps<HTMLDivElement>
}


// if validation text prop exists, then we know it should be true
export function FormTextInput({ type = 'text', label, name, validationText = "", ...rest }: IFormTextInputProps) {
  return (
    <>
      <Label
        id={`text-input-${name}`}
        name={name}
        className="rw-label"
        errorClassName="rw-label rw-label-error"
        {...rest.labelProps}
      >
        {label}
      </Label>

      {type === 'password' ? (
        <>
          <PasswordField
            name={name}
            className="rw-input"
            errorClassName="rw-input rw-input-error"
            validation={
              validationText
                ? {
                    required: {
                      value: true,
                      message: validationText,
                    },
                  }
                : {}
            }
            {...rest.inputProps}
          />
          <FieldError name={name} className="rw-field-error" />
        </>
      ) : (
        <TextField
          name={name}
          className="rw-input"
          errorClassName="rw-input rw-input-error"
          validation={
            validationText
              ? {
                  required: {
                    value: true,
                    message: validationText,
                  },
                }
              : {}
          }
          {...rest.inputProps}
        />
      )}
      <FieldError name={name} className="rw-field-error" {...rest.fieldErrorProps} />
    </>
  )
}
```

2022-12-01 16:50 UTC, archae0pteryx commented on web/src/layouts/ProfileLayout/ProfileLayout.tsx
> +          <LinkItem to={routes.editEmail()}>Edit Email</LinkItem>
We should look into prerendering some of these routes... just wanted to say that outloud cause i'll forget =)

2022-12-01 16:59 UTC, archae0pteryx commented on web/src/pages/Profile/EditEmailPage/EditEmailPage.stories.tsx
> +import type { ComponentMeta } from '@storybook/react'
On storybook: Storybook is meant to isolate the individual components into the kind re-usable pieces i was describing above. It puts documenting their API's and the look/feel all in one place... Storybook should not be used on/for a whole "page" - something comprised of many components. Some components have multiple parts like a input with a label and that's fine for a single story (the storybook docs describe the why / how of isolating the components). I don't know if redwood generates these storybooks when you run the generator on a page, but if they do it might be worthwhile to bring it up / open an issue with them that the generator should create a story for an individual component to make it clear, not the whole page. I think a lot of ppl using redwood will generate a page and see the storybook for the page and not realize what it's actually for... does that make sense?

2022-12-01 17:06 UTC, archae0pteryx commented on web/tests/profile-email.spec.ts
> +    await loginPage.loginBasicUser(MOCK_USER_EMAIL)
Dont forget we also have a user session setup for us as well! We could skip all the login setup and just go straight to testing the actual edit page if you load that session state...

2022-12-01 17:11 UTC, archae0pteryx approved these changes
Some nit-picks, some suggestions, none of them suuuper important... There should prolly be some other tickets to update some of the things i pointed out... IMO this repo should be, "a gold standard" for programming patterns and I feel like there's some basic improvements that can still be made. The more we shuffle them to the side the deeper they get into the tech-debt bin. When someone else uses this they will look to the already written code for their guidance and thus spread more tech-debt... i digress.

2022-12-05 13:13 UTC, craineum commented on web/src/components/Profile/EditEmail/EditEmailForm.tsx
> +        <Label
I would agree with this, but the patterns we are using is just the generated things. When we start looking at styling and a component library (which is the next thing on the list). This will be a top priority.

2022-12-05 13:23 UTC, craineum commented on web/src/pages/Profile/EditEmailPage/EditEmailPage.stories.tsx
> +import type { ComponentMeta } from '@storybook/react'
One benefit of having pages implemented in storybook is that it allows someone to make a change to an underlying component and see how that would look on the pages it is used on. This would keep a UI/UX person in storybook without having to dive into the app.

Now, I am not saying that it means we should do it, but there are some reasons to doing it that way.

The downside is that it creates overhead that must be maintained, so is it worth it?

2022-12-06 13:29 UTC, craineum approved these changes
Going to merge this in as the ticket is now accomplished.

2022-12-06 13:29 UTC, merged