Feature/44 filter users
CodingZeal/redwood-template-app pull request #95
Opened 2022-10-07 22:24 UTC by zan-rosenthal

# Pull Request

Remove all sections below that are not needed

## Story

Include the ID in the branch name and link to the story here

Fix #<ISSUE_ID>

## Description

Clearly and concisely describe the feature.

## Analysis and Design

Analyze and attach design documentation.

## Solution

Describe your code changes in detail for reviewers.

## Screenshots

Post the output screenshots, if an UI is affected or added due to this feature.

## Affected Areas

List out the areas affected by your code change.

## Tests

Describe the tests.

## Was this feature tested on all browsers?

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Internet Explorer
- [ ] Safari

## Related PRs

Add any related pull requests

## Definition of Done

- [ ] README updated
- [ ] Tests written
- [ ] Acceptance criteria implement
- [ ] Code reviewed
- [ ] Feature accepted

## PR Comments Emoji Legend

😻 - `:heart_cat_eyes:` Compliment to code/idea/etc
♻️ - `:recycle:` Non-blocking proposed refactor
➕ - `:heavy_plus_sign:` Non-blocking proposed addition
🔥 - `:fire:` Non-blocking proposed removal
❓ - `:question:` Non-blocking question
⚠️ - `:warning:` Blocking comment that must be addressed before PR

## Gifs for life (required)

![mandatory](https://media.giphy.com/media/3otPoUygHpFbzM350A/giphy.gif)

2022-10-27 12:03 UTC, craineum reviewed
Looks great! A couple of questions.

2022-10-27 12:03 UTC, craineum commented on web/src/components/Admin/User/UsersCell/UsersCell.tsx
> +  const active = showInactive ? undefined : true
❓ Why `undefined` instead of `false` here?

2022-10-27 12:03 UTC, craineum commented on web/src/pages/Admin/User/UsersPage/UsersPage.tsx
> +import { useToggle } from 'src/lib/hooks'
❓ Why not import directly from `react-use` here? Are you trying to establish a known library of hooks for the app?

2022-10-27 12:05 UTC, archae0pteryx commented on api/src/services/users/users.ts
> +import { isEmpty, isNil, reject } from 'ramda'
excited that you added ramda!'

2022-10-27 12:11 UTC, craineum commented on api/src/services/users/users.ts
> +import { isEmpty, isNil, reject } from 'ramda'
I was surprised, since he didn't add it to the `package.json`, which means it was already there?!?

2022-10-27 22:42 UTC, zan-rosenthal commented on web/src/pages/Admin/User/UsersPage/UsersPage.tsx
> +import { useToggle } from 'src/lib/hooks'
I think my instinct was to wrap it in case it ever became less supported, then we could replace things under the hood. Maybe not necessary though. It looks pretty popular. I can just use it directly.

2022-10-27 22:43 UTC, zan-rosenthal commented on api/src/services/users/users.ts
> +}
@craineum @archae0pteryx I feel like this maybe belongs in it's own file, but I wasn't sure where to put it.

2022-10-27 22:43 UTC, zan-rosenthal commented on api/src/services/users/users.ts
> +import { isEmpty, isNil, reject } from 'ramda'
Yeah, ramda was already there. This brings up a good questions though, should we add ramda to this? Do you think using ramda would disuade anyone from using it?

2022-10-27 22:44 UTC, zan-rosenthal commented on web/src/components/Admin/User/UsersCell/UsersCell.tsx
> +  const active = showInactive ? undefined : true
@craineum On the backend, it's filtering `where: { active: false }` or true. If you pass it one or the other, it will only show active or inactive, where as, if you pass it false, it will show both.

2022-10-28 12:15 UTC, craineum requested changes
I resolved the conflicts, and it looks like there could be a couple minor changes. But looks great after that!

2022-10-28 12:15 UTC, craineum commented on web/src/components/Admin/User/Users/Users.tsx
> +                <input
🔥 Looks like this isn't doing anything, not sure why, but it can be removed. I don't think we need the toggle in here twice.

2022-10-28 12:15 UTC, craineum commented on api/src/services/users/users.ts
> +}
@zan-rosenthal
♻️ Good point. This could be reused other places. There is a `api/src/lib` directory that would work. There is even a `db.ts` file in there that we could add a named export to it.

2022-10-28 12:15 UTC, craineum commented on api/src/services/users/users.ts
> +import { isEmpty, isNil, reject } from 'ramda'
I'm okay to use Ramda for this kind of a thing that is more root level especially if we include it in the `db.ts` lib file.

2022-10-28 12:15 UTC, craineum commented on web/src/components/Admin/User/Users/Users.tsx
> +const checkboxInputTag = (label, checked = true) => {
❓ What was the reasoning for defaulting this to `true`?

2022-10-28 12:15 UTC, craineum commented on web/src/components/Admin/User/UsersCell/UsersCell.tsx
> +export const beforeQuery = ({
😻 I didn't know about this!

2022-10-28 12:15 UTC, craineum commented on web/src/pages/Admin/User/UsersPage/UsersPage.tsx
> +import { useToggle } from 'src/lib/hooks'
👍 That is good reasoning, between that and having a central place for hooks to see what is available, I am good with it as is.

2022-10-28 18:27 UTC, zan-rosenthal commented on web/src/components/Admin/User/Users/Users.tsx
> +const checkboxInputTag = (label, checked = true) => {
When I originally added it, there wasn't an argument for checked, and I think there was somewhere where nothing was being passed.

2022-10-28 18:27 UTC, zan-rosenthal commented on web/src/components/Admin/User/Users/Users.tsx
> +                <input
Whoops. Think this is a rebase artifact. I had it here in an earlier commit and then moved it up to a parent component.

2022-10-28 20:13 UTC, craineum approved these changes
LGTM! 🚀

2022-10-28 20:14 UTC, merged